
# Python CircleCI 2.1 configuration file
#

version: 2.1

executors:
  python_executor:
    docker:
      - image: python:3.8-alpine


jobs:
  install-dependencies:
    executor: python_executor
    working_directory: ~/repo
    steps:
      - run:
          name: install dependencies
          command: |
            pip install twine wheel

  build-package:
    executor: python_executor
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: build wheel package
          command: |
            cd ~/repo
            python setup.py bdist_wheel

  deploy-package:
    executor: python_executor
    working_directory: ~/repo
    steps:
      - run:
          name: run twine and upload wheel
          command: |
            cd ~/repo
            twine -u $PYPI_USERNAME -p $PYPI_PASSWORD --verbose  ./dist/*

workflows:
  version: 2.1
  workflows-build-package:
    jobs:
      - install-dependencies
      - build-package:
          filters:
            tags:
              only: /V([0-9]+\.[0-9]+\.[0-9]+)/
            branches:
              only:
                - release
      - deploy-package:
          requires:
            - build-package
