

# Python CircleCI 2.1 configuration file
#

version: 2.1

executors:
  python_executor:
    docker:
      - image: python:3.8


jobs:
  deploy-package:
    executor: python_executor
    working_directory: ~/repo
    steps:
      - run:
          name: install dependencies
          command: |
            pip install twine wheel
      - checkout
      - run:
          name: Build Wheel Package
          command: |
            cd ~/repo
            python setup.py bdist_wheel
      - run:
          name: Run Twine and Upload Wheel Packet
          command: |
            cd ~/repo
            twine upload -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} --verbose  ./dist/*

workflows:
  version: 2.1
  workflows-build-package:
    jobs:
      - deploy-package:
          filters:
            tags:
              only: /V([0-9]+\.[0-9]+\.[0-9]+)/
            branches:
              only:
                - release
